name: Hugo build

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build Hugo pages
      uses: jakejarvis/hugo-build-action@v0.79.0
      with:
        args: --gc --minify --cleanDestinationDir --buildDrafts

    - name: Deploy website
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_hostname }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/
        server-dir: httpdocs/gasbrugherio/